name: FlutterOnlineDetection
description: Mobile application real-time object detectio.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  camera: ^0.5.8+11
  tflite_flutter: ^0.5.0
  tflite_flutter_helper: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/detect.tflite
    - assets/labelmap.txt
